export const cards = [
  {
    id: 1,
    title: "Ragavan, Nimble Pilferer",
    url: "https://www.mtgpics.com/pics/big/mh2/138.jpg",
    originalPrice: 65.69,
    salePrice: 59.12,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Sheoldred, the Apocalypse",
    url: "https://www.mtgpics.com/pics/big/dmu/107.jpg",
    originalPrice: 49.92,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Urza's Saga",
    url: "https://www.mtgpics.com/pics/big/mh2/259.jpg",
    originalPrice: 31.02,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Leyline Binding",
    url: "https://www.mtgpics.com/pics/big/dmu/024.jpg",
    originalPrice: 12.53,
    salePrice: 11.27,
    rating: 4.5,
  },
  {
    id: 5,
    title: "Boseiju, Who Endures",
    url: "https://www.mtgpics.com/pics/big/neo/266.jpg",
    originalPrice: 24.21,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "Fable of the Mirror Breaker",
    url: "https://www.mtgpics.com/pics/big/neo/141.jpg",
    originalPrice: 16.42,
    salePrice: 14.78,
    rating: 5,
  },
  {
    id: 7,
    title: "Mox Amber",
    url: "https://www.mtgpics.com/pics/big/brr/035.jpg",
    originalPrice: 51.69,
    salePrice: 46.52,
    rating: 4,
  },
  {
    id: 8,
    title: "Liliana of the Veil",
    url: "https://www.mtgpics.com/pics/big/dmu/097.jpg",
    originalPrice: 26.97,
    salePrice: 24.27,
    rating: 4.5,
  },
  {
    id: 9,
    title: "Scalding tarn",
    url: "https://www.mtgpics.com/pics/big/mh2/254.jpg",
    originalPrice: 20.35,
    salePrice: 18.32,
    rating: 4.5,
  },
  {
    id: 10,
    title: "Ledger Shredder",
    url: "https://www.mtgpics.com/pics/big/snc/046.jpg",
    originalPrice: 17.2,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "Endurance",
    url: "https://www.mtgpics.com/pics/big/mh2/157.jpg",
    originalPrice: 32.89,
    salePrice: 29.6,
    rating: 5,
  },
  {
    id: 12,
    title: "Wrenn and Six",
    url: "https://www.mtgpics.com/pics/big/2x2/296.jpg",
    originalPrice: 55.15,
    salePrice: 49.64,
    rating: 4.5,
  },
];
